name: Node.js CI

on:
  push:
    paths:
      - 'auth-service/**'
  pull_request:
    paths:
      - 'auth-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: auth-service

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: auth-service

      - name: Run tests
        run: npm test
        working-directory: auth-service

